// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Empty struct {
}

type ErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type JwtAuth struct {
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`
}

type MeResp struct {
	UserID string `json:"user_id"`
	Phone  string `json:"phone"`
}

type RefreshResp struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Message string `json:"message"`
}
