// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/jieyuc/inkforge/services/console/internal/handler/auth"
	user "github.com/jieyuc/inkforge/services/console/internal/handler/user"
	"github.com/jieyuc/inkforge/services/console/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	authRoutes := []rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/login",
			Handler: auth.LoginHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/logout",
			Handler: auth.LogoutHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/refresh",
			Handler: auth.RefreshHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/register",
			Handler: auth.RegisterHandler(serverCtx),
		},
	}

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthRateLimit},
			authRoutes...,
		),
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/me",
				Handler: user.MeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
