// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/jieyuc/inkforge/services/console/internal/handler/auth"
	namespace "github.com/jieyuc/inkforge/services/console/internal/handler/namespace"
	user "github.com/jieyuc/inkforge/services/console/internal/handler/user"
	"github.com/jieyuc/inkforge/services/console/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	authRoutes := []rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/login",
			Handler: auth.LoginHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/logout",
			Handler: auth.LogoutHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/refresh",
			Handler: auth.RefreshHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/register",
			Handler: auth.RegisterHandler(serverCtx),
		},
	}

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{serverCtx.AuthRateLimit}, authRoutes...),
		rest.WithPrefix("/api/v1/auth"),
	)

	nsRoutes := []rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/namespaces",
			Handler: namespace.ListNamespacesHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/namespaces",
			Handler: namespace.CreateNamespaceHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/namespaces/:nsSlug",
			Handler: namespace.GetNamespaceHandler(serverCtx),
		},
		{
			Method:  http.MethodPatch,
			Path:    "/namespaces/:nsSlug",
			Handler: namespace.PatchNamespaceHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/namespaces/:nsSlug/archive",
			Handler: namespace.ArchiveNamespaceHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/namespaces/:nsSlug/restore",
			Handler: namespace.RestoreNamespaceHandler(serverCtx),
		},
	}

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{serverCtx.TenantCtx}, nsRoutes...),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/me"),
	)

	apiRoutes := []rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/me",
			Handler: user.MeHandler(serverCtx),
		},
	}

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{serverCtx.TenantCtx}, apiRoutes...),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
