// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	consoleNamespacesFieldNames          = builder.RawFieldNames(&ConsoleNamespaces{})
	consoleNamespacesRows                = strings.Join(consoleNamespacesFieldNames, ",")
	consoleNamespacesRowsExpectAutoSet   = strings.Join(stringx.Remove(consoleNamespacesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	consoleNamespacesRowsWithPlaceHolder = strings.Join(stringx.Remove(consoleNamespacesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	consoleNamespacesModel interface {
		Insert(ctx context.Context, data *ConsoleNamespaces) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ConsoleNamespaces, error)
		FindOneByTenantIdNsSlug(ctx context.Context, tenantId string, nsSlug string) (*ConsoleNamespaces, error)
		Update(ctx context.Context, data *ConsoleNamespaces) error
		Delete(ctx context.Context, id string) error
	}

	defaultConsoleNamespacesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ConsoleNamespaces struct {
		Id                 string         `db:"id"`
		TenantId           string         `db:"tenant_id"` // account isolation domain; personal MVP equals user id
		NsSlug             string         `db:"ns_slug"`
		DisplayName        string         `db:"display_name"`
		Description        sql.NullString `db:"description"`
		Tags               sql.NullString `db:"tags"`   // opaque JSON tags
		Status             string         `db:"status"` // active|archived
		DefaultChannelSlug sql.NullString `db:"default_channel_slug"`
		ArchivedAt         sql.NullTime   `db:"archived_at"`
		QuotaPromptsMax    sql.NullInt64  `db:"quota_prompts_max"` // NULL inherit account/platform merge
		PromptCount        uint64         `db:"prompt_count"`
		CreatedAt          time.Time      `db:"created_at"`
		UpdatedAt          time.Time      `db:"updated_at"`
	}
)

func newConsoleNamespacesModel(conn sqlx.SqlConn) *defaultConsoleNamespacesModel {
	return &defaultConsoleNamespacesModel{
		conn:  conn,
		table: "`console_namespaces`",
	}
}

func (m *defaultConsoleNamespacesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultConsoleNamespacesModel) FindOne(ctx context.Context, id string) (*ConsoleNamespaces, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", consoleNamespacesRows, m.table)
	var resp ConsoleNamespaces
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConsoleNamespacesModel) FindOneByTenantIdNsSlug(ctx context.Context, tenantId string, nsSlug string) (*ConsoleNamespaces, error) {
	var resp ConsoleNamespaces
	query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `ns_slug` = ? limit 1", consoleNamespacesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, tenantId, nsSlug)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConsoleNamespacesModel) Insert(ctx context.Context, data *ConsoleNamespaces) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, consoleNamespacesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.TenantId, data.NsSlug, data.DisplayName, data.Description, data.Tags, data.Status, data.DefaultChannelSlug, data.ArchivedAt, data.QuotaPromptsMax, data.PromptCount)
	return ret, err
}

func (m *defaultConsoleNamespacesModel) Update(ctx context.Context, newData *ConsoleNamespaces) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, consoleNamespacesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TenantId, newData.NsSlug, newData.DisplayName, newData.Description, newData.Tags, newData.Status, newData.DefaultChannelSlug, newData.ArchivedAt, newData.QuotaPromptsMax, newData.PromptCount, newData.Id)
	return err
}

func (m *defaultConsoleNamespacesModel) tableName() string {
	return m.table
}
