// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	consolePromptsFieldNames          = builder.RawFieldNames(&ConsolePrompts{})
	consolePromptsRows                = strings.Join(consolePromptsFieldNames, ",")
	consolePromptsRowsExpectAutoSet   = strings.Join(stringx.Remove(consolePromptsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	consolePromptsRowsWithPlaceHolder = strings.Join(stringx.Remove(consolePromptsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	consolePromptsModel interface {
		Insert(ctx context.Context, data *ConsolePrompts) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ConsolePrompts, error)
		FindOneByNsIdPromptKey(ctx context.Context, nsId string, promptKey string) (*ConsolePrompts, error)
		Update(ctx context.Context, data *ConsolePrompts) error
		Delete(ctx context.Context, id string) error
	}

	defaultConsolePromptsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ConsolePrompts struct {
		Id          string         `db:"id"`
		TenantId    string         `db:"tenant_id"` // account isolation domain
		NsId        string         `db:"ns_id"`
		PromptKey   string         `db:"prompt_key"`
		Title       sql.NullString `db:"title"`
		Tags        sql.NullString `db:"tags"`
		OwnerUserId sql.NullString `db:"owner_user_id"`
		DraftBody   string         `db:"draft_body"`
		DraftSchema sql.NullString `db:"draft_schema"` // JSON array of variable definitions
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newConsolePromptsModel(conn sqlx.SqlConn) *defaultConsolePromptsModel {
	return &defaultConsolePromptsModel{
		conn:  conn,
		table: "`console_prompts`",
	}
}

func (m *defaultConsolePromptsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultConsolePromptsModel) FindOne(ctx context.Context, id string) (*ConsolePrompts, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", consolePromptsRows, m.table)
	var resp ConsolePrompts
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConsolePromptsModel) FindOneByNsIdPromptKey(ctx context.Context, nsId string, promptKey string) (*ConsolePrompts, error) {
	var resp ConsolePrompts
	query := fmt.Sprintf("select %s from %s where `ns_id` = ? and `prompt_key` = ? limit 1", consolePromptsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, nsId, promptKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConsolePromptsModel) Insert(ctx context.Context, data *ConsolePrompts) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, consolePromptsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.TenantId, data.NsId, data.PromptKey, data.Title, data.Tags, data.OwnerUserId, data.DraftBody, data.DraftSchema)
	return ret, err
}

func (m *defaultConsolePromptsModel) Update(ctx context.Context, newData *ConsolePrompts) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, consolePromptsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TenantId, newData.NsId, newData.PromptKey, newData.Title, newData.Tags, newData.OwnerUserId, newData.DraftBody, newData.DraftSchema, newData.Id)
	return err
}

func (m *defaultConsolePromptsModel) tableName() string {
	return m.table
}
