// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	consolePromptChannelPointersFieldNames          = builder.RawFieldNames(&ConsolePromptChannelPointers{})
	consolePromptChannelPointersRows                = strings.Join(consolePromptChannelPointersFieldNames, ",")
	consolePromptChannelPointersRowsExpectAutoSet   = strings.Join(stringx.Remove(consolePromptChannelPointersFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	consolePromptChannelPointersRowsWithPlaceHolder = strings.Join(stringx.Remove(consolePromptChannelPointersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	consolePromptChannelPointersModel interface {
		Insert(ctx context.Context, data *ConsolePromptChannelPointers) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ConsolePromptChannelPointers, error)
		FindOneByPromptIdChannelSlug(ctx context.Context, promptId string, channelSlug string) (*ConsolePromptChannelPointers, error)
		Update(ctx context.Context, data *ConsolePromptChannelPointers) error
		Delete(ctx context.Context, id string) error
	}

	defaultConsolePromptChannelPointersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ConsolePromptChannelPointers struct {
		Id          string    `db:"id"`
		TenantId    string    `db:"tenant_id"`
		NsId        string    `db:"ns_id"`
		PromptId    string    `db:"prompt_id"`
		ChannelSlug string    `db:"channel_slug"`
		VersionId   string    `db:"version_id"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newConsolePromptChannelPointersModel(conn sqlx.SqlConn) *defaultConsolePromptChannelPointersModel {
	return &defaultConsolePromptChannelPointersModel{
		conn:  conn,
		table: "`console_prompt_channel_pointers`",
	}
}

func (m *defaultConsolePromptChannelPointersModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultConsolePromptChannelPointersModel) FindOne(ctx context.Context, id string) (*ConsolePromptChannelPointers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", consolePromptChannelPointersRows, m.table)
	var resp ConsolePromptChannelPointers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConsolePromptChannelPointersModel) FindOneByPromptIdChannelSlug(ctx context.Context, promptId string, channelSlug string) (*ConsolePromptChannelPointers, error) {
	var resp ConsolePromptChannelPointers
	query := fmt.Sprintf("select %s from %s where `prompt_id` = ? and `channel_slug` = ? limit 1", consolePromptChannelPointersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, promptId, channelSlug)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConsolePromptChannelPointersModel) Insert(ctx context.Context, data *ConsolePromptChannelPointers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, consolePromptChannelPointersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.TenantId, data.NsId, data.PromptId, data.ChannelSlug, data.VersionId)
	return ret, err
}

func (m *defaultConsolePromptChannelPointersModel) Update(ctx context.Context, newData *ConsolePromptChannelPointers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, consolePromptChannelPointersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TenantId, newData.NsId, newData.PromptId, newData.ChannelSlug, newData.VersionId, newData.Id)
	return err
}

func (m *defaultConsolePromptChannelPointersModel) tableName() string {
	return m.table
}
