// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	consolePromptVersionsFieldNames          = builder.RawFieldNames(&ConsolePromptVersions{})
	consolePromptVersionsRows                = strings.Join(consolePromptVersionsFieldNames, ",")
	consolePromptVersionsRowsExpectAutoSet   = strings.Join(stringx.Remove(consolePromptVersionsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	consolePromptVersionsRowsWithPlaceHolder = strings.Join(stringx.Remove(consolePromptVersionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	consolePromptVersionsModel interface {
		Insert(ctx context.Context, data *ConsolePromptVersions) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ConsolePromptVersions, error)
		FindOneByPromptIdVersionNum(ctx context.Context, promptId string, versionNum uint64) (*ConsolePromptVersions, error)
		Update(ctx context.Context, data *ConsolePromptVersions) error
		Delete(ctx context.Context, id string) error
	}

	defaultConsolePromptVersionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ConsolePromptVersions struct {
		Id              string         `db:"id"`
		TenantId        string         `db:"tenant_id"`
		NsId            string         `db:"ns_id"`
		PromptId        string         `db:"prompt_id"`
		VersionNum      uint64         `db:"version_num"` // monotonic per prompt_id
		VersionLabel    string         `db:"version_label"`
		Body            string         `db:"body"`
		SchemaJson      sql.NullString `db:"schema_json"`
		ChangeNote      sql.NullString `db:"change_note"`
		CreatedByUserId string         `db:"created_by_user_id"`
		CreatedAt       time.Time      `db:"created_at"`
	}
)

func newConsolePromptVersionsModel(conn sqlx.SqlConn) *defaultConsolePromptVersionsModel {
	return &defaultConsolePromptVersionsModel{
		conn:  conn,
		table: "`console_prompt_versions`",
	}
}

func (m *defaultConsolePromptVersionsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultConsolePromptVersionsModel) FindOne(ctx context.Context, id string) (*ConsolePromptVersions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", consolePromptVersionsRows, m.table)
	var resp ConsolePromptVersions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConsolePromptVersionsModel) FindOneByPromptIdVersionNum(ctx context.Context, promptId string, versionNum uint64) (*ConsolePromptVersions, error) {
	var resp ConsolePromptVersions
	query := fmt.Sprintf("select %s from %s where `prompt_id` = ? and `version_num` = ? limit 1", consolePromptVersionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, promptId, versionNum)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConsolePromptVersionsModel) Insert(ctx context.Context, data *ConsolePromptVersions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, consolePromptVersionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.TenantId, data.NsId, data.PromptId, data.VersionNum, data.VersionLabel, data.Body, data.SchemaJson, data.ChangeNote, data.CreatedByUserId)
	return ret, err
}

func (m *defaultConsolePromptVersionsModel) Update(ctx context.Context, newData *ConsolePromptVersions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, consolePromptVersionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TenantId, newData.NsId, newData.PromptId, newData.VersionNum, newData.VersionLabel, newData.Body, newData.SchemaJson, newData.ChangeNote, newData.CreatedByUserId, newData.Id)
	return err
}

func (m *defaultConsolePromptVersionsModel) tableName() string {
	return m.table
}
